# Install and start the rabbitmq service
#
- name: Install RabbitMQ apt dependencies
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.apt:
    name:
    - rabbitmq-server

- when: ansible_service_mgr == "systemd"
  block:
  # see https://github.com/marvel-nccr/quantum-mobile/issues/111
  - name: Ensure correct RabbitMQ shutdown (systemd)
    become: true
    become_user: "{{ root_user }}"
    lineinfile:
      path: /lib/systemd/system/rabbitmq-server.service
      regexp: ExecStop=/usr/sbin/rabbitmqctl stop
      line: ExecStop=/usr/sbin/rabbitmqctl shutdown
  - name: Start RabbitMQ service (systemd)
    become: true
    become_user: "{{ root_user }}"
    service:
      name: "rabbitmq-server"
      state: "started"
      enabled: true

- when: ansible_service_mgr != "systemd"
  block:
  - name: Check if RabbitMQ is running (non-systemd)
    shell: pgrep rabbitmq
    changed_when: false
  rescue:
  - name: Start RabbitMQ (non-systemd)
    become: true
    become_user: "{{ root_user }}"
    shell: rabbitmq-server > /dev/null 2>&1 &
