name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  galaxy-name: "marvel-nccr.aiida_cws"

jobs:

  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: pre-commit/action@v2.0.0

  molecule:

    strategy:
      matrix:
        distro: [ubuntu1804, ubuntu2004]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        path: ${{ env.galaxy-name }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: |
        pip install --upgrade pip
        pip --version

    - name: Install requirements
      run: |
        pip install wheel
        pip install -r requirements.txt
      working-directory: ${{ env.galaxy-name }}

    - name: Run molecule
      run: molecule test
      working-directory: ${{ env.galaxy-name }}
      env:
        MOLECULE_DISTRO: ${{ matrix.distro }}
